FROM node:16.20-alpine

ENV NODE_ENV development

WORKDIR /app

COPY ./package.json /app

RUN npm install

ENV PORT=3000

COPY . .

ENV PORT=3000


# FROM node:16.20 AS base
# WORKDIR /app
# COPY package.json /app/package.json
# # COPY package-lock.json /app/package-lock.json
# RUN npm i
# COPY . /app
# # ENV PORT=3000

# FROM base AS build
# RUN npm run build

# FROM nginx:alpine
# COPY --from=build /app/.nginx/nginx.conf /etc/nginx/conf.d/default.conf
# WORKDIR /usr/share/nginx/html
# RUN rm -rf ./*
# COPY --from=build /app/build .
# ENTRYPOINT ["nginx", "-g", "daemon off;"]


