FROM node:16.20.0-alpine3.17 as base


WORKDIR /app

COPY package*.json ./

RUN npm install --only=production --omit=dev

COPY . .

RUN npm prune --production

FROM node:16.20.0-alpine3.17

ENV NODE_ENV=production

RUN npm install -g env-cmd

WORKDIR /app

COPY --from=base /app ./

EXPOSE 4000




