version: "3.8"
services:
  mysql: # shell into container: docker exec -it af1046f4563b bash
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - global_mysql-data:/var/lib/mysql
      # - mysql-data:/var/lib/mysql
      - mysql-initdb:/docker-entrypoint-initdb.d/init.sql

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - global_mongo-data:/data/db
      - mongo-conf:/etc/mongo
      - mongo-configdb:/data/configdb
      # - mongo-data:/data/db
      # - global_mongo-conf:/etc/mongo
      # - global_mongo-configdb:/data/configdb

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}

volumes:
  global_mysql-data:
    external: true
  global_mongo-data:
    external: true
  mysql-data:
  mysql-initdb:
  # mongo-data:
  mongo-conf:
  mongo-configdb:
